# Generated by Django 3.2.3 on 2021-08-20 09:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_projectworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworks',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
