# Generated by Django 3.2.3 on 2021-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_projectworks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworks',
            name='rank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
